version: '3'

networks:
  redis-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.1.0/24

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: liuzihao520
      MYSQL_DATABASE: blog
      LANG: C.UTF-8
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # 注意这里的路径映射
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "36379:6379"
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis.log:/log/redis.log
    #配置文件启动
    command: redis-server /usr/local/etc/redis/redis.conf
  blog:
    build:
      context: .
      dockerfile: Dockerfile  # 指定你的 Dockerfile 文件路径
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis
    volumes:
      - ../blog-statics//img:/app/statics/img  # 将本地图片文件夹挂载到容器中的对应路径
volumes:
  mysql_data:
  redis_data:
