app:
  name: "blog"
  mode: "dev"
  port: "80"
  start_time: "2024-01-16"
  machine_id: 1
auth:
  jwt_expire: 168 #一周时间
log:
  level: "info"
  filename: "./log/blog.log"
  max_size: 1
  max_age: 30
  max_backups: 7
mysql:
#  host: 127.0.0.1
  host: mysql
  username: "root"
  password: liuzihao520
  port: "3306"
  dbname: "blog"
  max_open_con: 200
  max_idle_con: 50
redis:
#  host: 127.0.0.1
  host: redis
  port: "6379"
  db: 0
  password:
  password: liuzihao520
  poll_size: 100
